default: &default
  adapter: postgresql
  encoding: unicode
  database: portal
  timeout: 5000
  pool: 5

development:
  <<: *default
  host: 192.168.1.88
  username: postgres
  password: 6k3vddrb2v

production:
  <<: *default
  host: 192.168.1.88
  username: postgres
  password: 6k3vddrb2v

test:
  <<: *default
  host: localhost
  username: postgres
  password: 1
