default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: portal
  username: postgres
  password: 1

test:
  <<: *default
  #database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  host: 192.168.1.88
  database: portal
  username: postgres
  password: 6k3vddrb2v
